### ISSUE TITLE
[1.10.2] NullPointerException: Ticking Screen

### ISSUE THREAD

**Issue by MCOfficer** [iChun/Hats#168]
```
java.lang.NullPointerException: Ticking screen
	at me.ichun.mods.hats.client.gui.GuiHatSelection.func_73876_c(GuiHatSelection.java:296)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1720)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

a curseforge user encountered this crash with their modpack, using the latest forge and hats (1.10.2).  I'll add more information as soon as they reply.

Reference:
[Full Crashlog](https://paste.ee/p/a4Zzg)
[Forum Thread](https://minecraft.curseforge.com/forums/general/general-discussion/232072-modpack-keeps-crashing)

**Comment by MCOfficer** [comment]
> It happened on startup or after a few minutes after "joining" a world, and i have remade my modpack completely so i don't know if it happens on recommended as well.
