### ISSUE TITLE
Hats not on thaumcraft mobs

### ISSUE THREAD

**Issue by tyggna** [iChun/Hats#172]
This is a super-low priority bug, I'm just going through my server logs and reporting all errors.
Basically the Hats mod can't add hats to Thaumcraft mobs because of an API call error, could be on their end, not sure, so submitting bugs to both packs.

Server version is forge-1.12.2-14.23.4.2705
Thaumcraft is 1.12.2-6.1.BETA17
Hats is 1.12.2-7.0.2

> [17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ExceptionInInitializerError
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.Class.forName0(Native Method)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.Class.forName(Class.java:264)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:         at me.ichun.mods.hats.common.thread.ThreadGetModMobSupport.run(ThreadGetModMobSupport.java:49)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.NullPointerException
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:         at thaumcraft.api.ThaumcraftApiHelper.makeCrystal(ThaumcraftApiHelper.java:362)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:         at thaumcraft.api.ThaumcraftApiHelper.makeCrystal(ThaumcraftApiHelper.java:372)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:         at thaumcraft.common.entities.monster.EntityPech.<clinit>(EntityPech.java:830)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:         ... 3 more

**Comment by AgentEpsilon** [comment]
I mentioned this in Azanor/thaumcraft-beta#556 as well - basically, it looks like Thaumcraft 6 changes the path to EntityPech, which causes the default Hats config at https://github.com/iChun/Hats/blob/master/src/main/resources/assets/hats/mod/HatModMobSupport.json to fail. This could be solved by removing the config entry in this repo, but that would cause any prior versions of Thaumcraft to have no Hats support for the Pech I believe.

**Comment by Zelda-Swordsman** [comment]
When combined with the morph mod, morphing into certain thaumcraft mobs causes a crash when in F5 mode.  It is ocurring in Foolcraft 3 modpack with added VanillaFix. VanillaFix says the culprit is the hats mod.
Crash Log
[https://paste.dimdev.org/opotozowig.mccrash](url)

**Comment by iChun** [comment]
I've removed the Pech entry for the mod mob support. Thanks for the issue report!
