### ISSUE TITLE
HeadInfo is not using a custom class but hasn;y set a head model

### ISSUE THREAD

**Issue by ModernGamingWorld** [iChun/Hats#210]
Is This something we need to worry about? It should up when starting up a server and was shown in console

[18.04 13:32:52] [Server] [Server thread/ERROR] [me.ic.mo.ic.ap.co.he.HeadInfo/]: HeadInfo is not using a custom class but hasn't set a head model.
[18.04 13:32:52] [Server] [Server thread/ERROR] [me.ic.mo.ic.ap.co.he.HeadInfo/]: Cannot find custom head info class: me.ichun.mods.ichunutil.common.head.entity.HeadHorse
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: java.lang.ClassNotFoundException: me.ichun.mods.ichunutil.common.head.entity.HeadHorse
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at java.base/java.lang.Class.forName0(Native Method)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at java.base/java.lang.Class.forName(Class.java:377)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer.deserialize(HeadInfo.java:589)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer.deserialize(HeadInfo.java:495)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at com.google.gson.Gson.fromJson(Gson.java:852)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at com.google.gson.Gson.fromJson(Gson.java:801)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at com.google.gson.Gson.fromJson(Gson.java:773)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at me.ichun.mods.ichunutil.common.head.HeadHandler.getHelper(HeadHandler.java:58)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at me.ichun.mods.hats.common.hats.HatHandler.canWearHat(HatHandler.java:128)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at me.ichun.mods.hats.common.core.EventHandlerServer.onEntityJoinedWorld(EventHandlerServer.java:54)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraftforge.eventbus.ASMEventHandler_398_EventHandlerServer_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:829)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.world.server.ChunkManager.func_219237_a_(ChunkManager.java:592)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.world.server.ChunkManager.func_219193_a_(ChunkManager.java:569)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:514)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:522)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:267)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:722)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:469)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:310)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:168)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621)
[18.04 13:32:52] [Server] [Server thread/INFO] [STDERR/]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:618]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)

**Comment by iChun** [comment]
It's a problem when you're updating from iChunUtil 10.1.0 to 10.2.0. If you
delete all the head info jsons from /config/ichunutil/heads/ and let the
mod reextract them, it should be fixed.

**Comment by ModernGamingWorld** [comment]
okay
