### ISSUE TITLE
FileNotFoundException HatModMobSupport.json

### ISSUE THREAD

**Issue by Macleykun** [iChun/Hats#213]
Saw that this file wasn't found during load.

```
java.io.FileNotFoundException: https://raw.githubusercontent.com/iChun/Hats/master/src/main/resources/assets/hats/mod/HatModMobSupport.json
 at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
 at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
 at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
 at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
 at java.security.AccessController.doPrivileged(AccessController.java:946)
 at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:988)
 at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
 at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
 at java.net.URL.openStream(URL.java:1068)
 at me.ichun.mods.hats.common.thread.ThreadGetModMobSupport.run(ThreadGetModMobSupport.java:41)
```

Latest forge on 1.12.2

**Comment by Macleykun** [comment]
A workaround for this is to use the local version. This can be done by going into the config folder, and editting the hats.cfg.
Change
```
    # Read the local mod mob support file (HatModMobSupport.json) from the /hats/ folder?
    # If turned off, it'll pull the online GitHub version.
    # Use this to do testing with custom mob hats.
    I:readLocalModMobSupport=0
```
to
```
    # Read the local mod mob support file (HatModMobSupport.json) from the /hats/ folder?
    # If turned off, it'll pull the online GitHub version.
    # Use this to do testing with custom mob hats.
    I:readLocalModMobSupport=1
```

If the following file: HatModMobSupport.json with the content of: {} is added to: mods/hats/
It’ll resolve the issue.

Hope this issue can be resolved from main/origin instead.

**Comment by iChun** [comment]
As we discussed over the iChunUtil repo, I won't be fixing this either, due
to mod age and it no longer being supported.

For extra trivia though, the JSON file is empty because no one ever
submitted mod mob support for Hats 😂

1.16.5's Hats uses an entirely different system in iChunUtil that's more
versatile and easier to add support to mobs for. As a result, multiple
people have added mod mob support for since its release.

**Comment by Macleykun** [comment]
Sure no problem :) Thanks for your work and replies! Have a great weekend!
Ah, i was afraid that was the case with the json :c kinda was a sad find, thanks again for commenting on the issues!
