### ISSUE TITLE
Erm...

### ISSUE THREAD

**Issue by Frizzledizzley** [iChun/Hats#234]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/28/21 1:23 PM
Description: Hats Hat Reader Thread crashed!

java.lang.NoSuchMethodError: me.ichun.mods.ichunutil.common.util.IOUtil.scourDirectoryForFiles(Ljava/nio/file/Path;Ljava/util/function/Function;)I
	at me.ichun.mods.hats.common.hats.HatResourceHandler.loadAllHats(HatResourceHandler.java:87) ~[?:10.3.2] {re:classloading}
	at me.ichun.mods.hats.common.thread.ThreadReadHats.run(ThreadReadHats.java:26) ~[?:10.3.2] {re:classloading}

**Comment by iChun** [comment]
Oops, update iChunUtil to 10.5.0
